version: "3"
services:
  web:
    build: .
    container_name: rangers_web_app
    ports:
      - "3000:3000"
    volumes: 
        - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: rangers_db
    ports:
      - "27017:27017"
